# Zrodla czasu, gdy jest internet
server time.cloudflare.com iburst
pool pool.ntp.org iburst
# Podawaj czas urzadzeniom w sieci lokalnej
allow all
# Bez internetu podawaj wlasny zegar (zegar komputera), zamiast milczec
local stratum 10
driftfile /var/lib/chrony/chrony.drift
makestep 1.0 3
